#server
server:
  # 项目contextPath，一般在正式发布版本中，我们不配置
  context-path: /
  # 该服务绑定IP地址，启动服务器时如本机不是该IP地址则抛出异常启动失败，只有特殊需求的情况下才配置
  #address: 192.168.0.101
  # 错误页，指定发生错误时，跳转的URL。请查看BasicErrorController源码便知
  error:
     path: /error
  # 服务端口
  port: 8089
  # session最大超时时间(分钟)，默认为30
  session:
    timeout: 60
  tomcat:
    # tomcat的URI编码
    uri-encoding: utf-8
    # tomcat最大线程数，默认为200
    max-threads: 500
    # 存放Tomcat的日志、Dump等文件的临时文件夹，默认为系统的tmp文件夹（如：C:\Users\Shanhy\AppData\Local\Temp）
    #basedir: G:/springboot-tomcat-tmp
    # 打开Tomcat的Access日志，并可以设置日志格式的方法：
    #server.tomcat.access-log-enabled=true
    #server.tomcat.access-log-pattern=

druid:
  driver-class-name: com.mysql.jdbc.Driver
  # 云票盒子 测试
  url: jdbc:mysql://120.79.210.194:3306/m_pay?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: bb123456
  initialSize: 5                                        #初始化连接大小
  minIdle: 5                                            #连接池最小空闲
  maxActive: 20                                         #连接池最大使用连接数量
  maxWait: 60000                                        #获取连接最大等待时间
  minEvictableIdleTimeMillis: 300000                    #配置一个连接在池中最小生存的时间，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000                  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒

mybatis:
  type-aliases-package: com.cjcx.pay.dto,com.cjcx.pay.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true


#开启AOP代理
spring:
  thymeleaf:
    cache: false
    mode: HTML5
    content-type: text/html
    encoding: UTF-8